version: 2.1

executors:
  muslim-lite-android-executor:
    docker:
      - image: circleci/android:api-29
    working_directory: ~/muslim-lite
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2048m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      TERM: muslim

  muslim-lite-gcloud-executor:
    docker:
      - image: google/cloud-sdk:latest
    working_directory: ~/muslim-lite
    environment:
      TERM: muslim

commands:
  store-muslim-lite-artifacts:
    description: "It stores Lint & Test artifacts"
    parameters:
      artifact-path:
        type: string
    steps:
      - store_artifacts:
          path: <.artifact-path>>

jobs:
  build:
    executor: muslim-lite-android-executor
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - run:
          name: Run AssembleDebug
          command: ./gradlew assembleDebug --stacktrace
      - run:
          name: Gather Lint results
          command: scripts/copy_lint_results.sh
      - store-plaid-artifacts:
          artifact-path: ci_results/lint
      # Persist build directory for all modules
      - persist_to_workspace:
          root: .
          paths:
            - build
            - ./**/build

workflows:
  version: 2
  build:
    jobs:
      - build